127.0.0.1 - - [27/Mar/2025 15:47:21] code 501, message Unsupported method ('GET')
127.0.0.1 - - [27/Mar/2025 15:47:21] "GET / HTTP/1.1" 501 -
127.0.0.1 - - [27/Mar/2025 15:47:21] code 501, message Unsupported method ('GET')
127.0.0.1 - - [27/Mar/2025 15:47:21] "GET /favicon.ico HTTP/1.1" 501 -
127.0.0.1 - - [27/Mar/2025 15:47:35] "POST / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 42790)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/home/felipe/Desktop/Github_folder/webhook_server/webhook_server.py", line 9, in do_POST
    subprocess.run(["/home/nsee/start_runner.sh"])
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nsee/start_runner.sh'
----------------------------------------
Traceback (most recent call last):
  File "/home/felipe/Desktop/Github_folder/webhook_server/webhook_server.py", line 13, in <module>
    httpd = HTTPServer(server_address, WebhookHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/felipe/Desktop/Github_folder/webhook_server/webhook_server.py", line 13, in <module>
    httpd = HTTPServer(server_address, WebhookHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
